auth_key = "c5fd96bf14ca49a5b1aa3ba5c6dd98cc"
OPENAI_API_KEY = "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"
pre_prompt = """
You are a tutorial creator. I will give you the transcript of parts of a video. 
- You must return the title of each part following this template: [Part 1:] *Title here*
- You must explain to the user how to perform the task of each part using bullet points and following this template: [Summary 1:] *Bullet points here*
- Remember to use the brackets []

Here are the parts of the transcript:

"""

fake_answer = """[Part 1:] How to Tie a Windsor Knot

[Summary 1:] Steps to tie a Windsor knot:

Start with your collar up and place the tie around your neck.
If you're right-handed, hold the wide end of the tie in your right hand and the narrow end in your left hand.
Remember that the longer you make the wide end, the lower the tie will hang.
[Part 2:] Crossing the Ends

[Summary 2:] Steps to cross the ends of the tie:

Line up your tie, ensuring the wide end is longer.
Cross each end over the wide end, bringing them over the top.
Leave about four inches (or 10 cm) on the narrow end.
With your left hand, take the wide end and thread it through the back of the opening.
[Part 3:] Wrapping and Threading

[Summary 3:] Steps to wrap and thread the tie:

Take the wide end with your left hand and wrap it all the way around the back.
Switch hands, ensuring the back of the tie is facing outward.
In your right hand, thread the wide end through the front of the opening, going through the front and down.
Thread it all the way through to the back.
[Part 4:] Creating the Knot

[Summary 4:] Steps to create the knot:

Place your left index finger on the knot.
With your other hand, wrap the wide end around the knot from right to left and grab it from behind.
Keep your index finger in place.
With your right hand, push the wide end through the back opening again, coming up and through from the back.
[Part 5:] Final Adjustments

[Summary 5:] Steps for final adjustments:

Thread the wide end through the hole created by your index finger.
Pull the tie down through the tunnel created by your finger.
Adjust and tighten the knot by gradually pulling the long end and the short end alternately.
Shape the knot as you go until it's symmetrical and triangular.
[Part 6:] Finishing Touch

[Summary 6:] Final step to complete the knot:

Pull your collar down to cover the knot.
You've successfully tied a full Windsor knot."""